DROP TABLE IF EXISTS `{prefix}_board_q`;
CREATE TABLE `{prefix}_board_q` ( `id` int(11) NOT NULL AUTO_INCREMENT, `module_id` int(11) NOT NULL, `category_id` int(11) NOT NULL, `sender` varchar(50) NOT NULL, `member_id` int(11) NOT NULL, `email` varchar(255) NOT NULL, `ip` varchar(50) NOT NULL, `create_date` int(11) NOT NULL, `last_update` int(11) NOT NULL, `visited` smallint(6) DEFAULT NULL, `comments` smallint(3) DEFAULT NULL, `comment_id` int(11) DEFAULT NULL, `commentator` varchar(50) DEFAULT NULL, `commentator_id` int(11) DEFAULT NULL, `comment_date` int(11) DEFAULT NULL, `picture` text DEFAULT NULL, `pictureW` int(11) DEFAULT NULL, `pictureH` int(11) DEFAULT NULL, `hassubpic` smallint(3) DEFAULT NULL, `can_reply` tinyint(1) NOT NULL DEFAULT 1, `published` tinyint(1) NOT NULL DEFAULT 1, `pin` tinyint(1) NOT NULL DEFAULT 0, `locked` tinyint(1) NOT NULL DEFAULT 0, `related` varchar(149) DEFAULT NULL, `topic` varchar(64) NOT NULL, `detail` text NOT NULL, PRIMARY KEY (`id`), FULLTEXT KEY `topic` (`topic`), FULLTEXT KEY `detail` (`detail`), FULLTEXT KEY `topic_2` (`topic`), FULLTEXT KEY `detail_2` (`detail`), FULLTEXT KEY `topic_3` (`topic`), FULLTEXT KEY `detail_3` (`detail`) ) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci
DROP TABLE IF EXISTS `{prefix}_board_r`;
CREATE TABLE `{prefix}_board_r` ( `id` int(11) NOT NULL AUTO_INCREMENT, `module_id` int(11) NOT NULL, `index_id` int(11) NOT NULL, `detail` text NOT NULL, `sender` varchar(50) NOT NULL, `member_id` int(11) NOT NULL, `email` varchar(255) NOT NULL, `ip` varchar(50) NOT NULL, `last_update` int(11) NOT NULL, `picture` text DEFAULT NULL, `pictureW` int(11) DEFAULT NULL, `pictureH` int(11) DEFAULT NULL, PRIMARY KEY (`id`), FULLTEXT KEY `detail` (`detail`), FULLTEXT KEY `detail_2` (`detail`), FULLTEXT KEY `detail_3` (`detail`) ) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci
DROP TABLE IF EXISTS `{prefix}_category`;
CREATE TABLE `{prefix}_category` ( `id` int(11) NOT NULL AUTO_INCREMENT, `module_id` int(11) NOT NULL, `category_id` int(11) NOT NULL, `group_id` int(11) DEFAULT 0, `config` text DEFAULT NULL, `c1` int(11) DEFAULT NULL, `c2` int(11) DEFAULT NULL, `topic` text NOT NULL, `detail` text DEFAULT NULL, `icon` text DEFAULT NULL, `published` enum('0','1') NOT NULL DEFAULT '1', PRIMARY KEY (`id`) ) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci
DROP TABLE IF EXISTS `{prefix}_comment`;
CREATE TABLE `{prefix}_comment` ( `id` int(11) NOT NULL AUTO_INCREMENT, `module_id` int(11) NOT NULL, `index_id` int(11) NOT NULL, `detail` text NOT NULL, `sender` varchar(50) NOT NULL, `member_id` int(11) NOT NULL, `email` varchar(255) NOT NULL, `ip` varchar(50) NOT NULL, `last_update` int(11) NOT NULL, `picture` text DEFAULT NULL, `pictureW` int(11) DEFAULT NULL, `pictureH` int(11) DEFAULT NULL, PRIMARY KEY (`id`), FULLTEXT KEY `detail` (`detail`), FULLTEXT KEY `detail_2` (`detail`), FULLTEXT KEY `detail_3` (`detail`) ) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci
DROP TABLE IF EXISTS `{prefix}_counter`;
CREATE TABLE `{prefix}_counter` ( `id` int(11) NOT NULL AUTO_INCREMENT, `counter` int(11) NOT NULL, `visited` int(11) NOT NULL, `pages_view` int(11) NOT NULL, `time` int(11) NOT NULL, `date` date NOT NULL, PRIMARY KEY (`id`) ) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci
DROP TABLE IF EXISTS `{prefix}_download`;
CREATE TABLE `{prefix}_download` ( `id` int(11) NOT NULL AUTO_INCREMENT, `module_id` int(11) NOT NULL, `category_id` smallint(5) DEFAULT NULL, `member_id` int(11) NOT NULL, `detail` varchar(200) NOT NULL, `last_update` int(11) NOT NULL, `name` varchar(50) NOT NULL, `ext` varchar(5) NOT NULL, `size` int(11) NOT NULL, `file` varchar(255) NOT NULL, `downloads` int(11) NOT NULL, `reciever` text NOT NULL, PRIMARY KEY (`id`) ) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci
DROP TABLE IF EXISTS `{prefix}_edocument`;
CREATE TABLE `{prefix}_edocument` ( `id` int(11) NOT NULL AUTO_INCREMENT, `module_id` int(11) NOT NULL, `sender_id` int(11) NOT NULL, `reciever` text NOT NULL, `last_update` int(11) NOT NULL, `downloads` int(11) NOT NULL, `document_no` varchar(20) NOT NULL, `detail` text NOT NULL, `topic` varchar(50) NOT NULL, `ext` varchar(4) NOT NULL, `size` double NOT NULL, `file` varchar(15) NOT NULL, `ip` varchar(50) DEFAULT NULL, PRIMARY KEY (`id`) ) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci
DROP TABLE IF EXISTS `{prefix}_edocument_download`;
CREATE TABLE `{prefix}_edocument_download` ( `id` int(10) NOT NULL AUTO_INCREMENT, `module_id` int(10) NOT NULL, `document_id` int(10) NOT NULL, `member_id` int(10) NOT NULL, `downloads` int(10) NOT NULL, `last_update` int(10) NOT NULL, PRIMARY KEY (`id`) ) ENGINE=MyISAM DEFAULT CHARSET=utf8
DROP TABLE IF EXISTS `{prefix}_emailtemplate`;
CREATE TABLE `{prefix}_emailtemplate` ( `id` int(10) NOT NULL AUTO_INCREMENT, `module` varchar(20) NOT NULL, `email_id` int(10) NOT NULL, `language` varchar(2) NOT NULL, `from_email` text NOT NULL, `copy_to` text NOT NULL, `name` text NOT NULL, `subject` text NOT NULL, `detail` text NOT NULL, `last_update` int(11) NOT NULL, PRIMARY KEY (`id`) ) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci
DROP TABLE IF EXISTS `{prefix}_eventcalendar`;
CREATE TABLE `{prefix}_eventcalendar` ( `id` int(11) NOT NULL AUTO_INCREMENT, `module_id` int(11) NOT NULL, `topic` varchar(64) NOT NULL, `detail` text NOT NULL, `description` varchar(149) NOT NULL, `keywords` varchar(149) NOT NULL, `member_id` int(11) NOT NULL, `create_date` datetime DEFAULT NULL, `last_update` int(11) NOT NULL, `begin_date` datetime DEFAULT NULL, `end_date` datetime DEFAULT NULL, `color` varchar(11) NOT NULL, `published` tinyint(1) NOT NULL, `published_date` date DEFAULT NULL, PRIMARY KEY (`id`) ) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci
DROP TABLE IF EXISTS `{prefix}_gallery`;
CREATE TABLE `{prefix}_gallery` ( `id` int(11) NOT NULL AUTO_INCREMENT, `module_id` int(11) NOT NULL, `album_id` int(11) NOT NULL, `image` varchar(15) NOT NULL, `last_update` int(11) NOT NULL, `count` int(11) NOT NULL, PRIMARY KEY (`id`) ) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci
DROP TABLE IF EXISTS `{prefix}_gallery_album`;
CREATE TABLE `{prefix}_gallery_album` ( `id` int(11) NOT NULL AUTO_INCREMENT, `module_id` int(11) NOT NULL, `topic` varchar(64) NOT NULL, `detail` varchar(200) NOT NULL, `last_update` int(11) NOT NULL, `count` int(11) NOT NULL, `visited` int(11) NOT NULL, PRIMARY KEY (`id`) ) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci
DROP TABLE IF EXISTS `{prefix}_index`;
CREATE TABLE `{prefix}_index` ( `id` int(11) NOT NULL AUTO_INCREMENT, `index` tinyint(1) NOT NULL DEFAULT 0, `module_id` int(11) NOT NULL, `category_id` int(11) DEFAULT NULL, `language` varchar(2) DEFAULT NULL, `sender` varchar(50) DEFAULT '', `member_id` int(11) NOT NULL, `email` varchar(255) DEFAULT NULL, `ip` varchar(50) NOT NULL, `create_date` int(11) NOT NULL, `last_update` int(11) NOT NULL, `visited` int(11) DEFAULT 0, `visited_today` int(11) DEFAULT 0, `comments` smallint(3) DEFAULT 0, `comment_id` int(11) DEFAULT 0, `commentator` varchar(50) DEFAULT NULL, `commentator_id` int(11) DEFAULT 0, `comment_date` int(11) DEFAULT NULL, `picture` text DEFAULT NULL, `pictureW` int(11) DEFAULT NULL, `pictureH` int(11) DEFAULT NULL, `hassubpic` smallint(3) DEFAULT NULL, `can_reply` tinyint(1) NOT NULL DEFAULT 0, `show_news` text DEFAULT NULL, `published` tinyint(1) NOT NULL DEFAULT 1, `pin` tinyint(1) NOT NULL DEFAULT 0, `locked` tinyint(1) NOT NULL DEFAULT 0, `published_date` date NOT NULL, `alias` varchar(64) DEFAULT NULL, `page` varchar(20) DEFAULT '', PRIMARY KEY (`id`,`module_id`) ) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci
DROP TABLE IF EXISTS `{prefix}_index_detail`;
CREATE TABLE `{prefix}_index_detail` ( `id` int(11) NOT NULL, `module_id` int(11) NOT NULL, `language` varchar(2) NOT NULL, `topic` varchar(255) NOT NULL, `description` varchar(255) NOT NULL, `detail` text NOT NULL, `keywords` varchar(255) NOT NULL, `relate` varchar(255) DEFAULT NULL, PRIMARY KEY (`id`,`module_id`,`language`), FULLTEXT KEY `topic` (`topic`), FULLTEXT KEY `detail` (`detail`) ) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci
DROP TABLE IF EXISTS `{prefix}_language`;
CREATE TABLE `{prefix}_language` ( `id` int(11) NOT NULL AUTO_INCREMENT, `key` text NOT NULL, `th` text DEFAULT NULL, `en` text DEFAULT NULL, `owner` varchar(20) NOT NULL, `type` varchar(5) NOT NULL, `js` tinyint(1) NOT NULL, PRIMARY KEY (`id`) ) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci
DROP TABLE IF EXISTS `{prefix}_logs`;
CREATE TABLE `{prefix}_logs` ( `time` datetime NOT NULL, `ip` varchar(32) NOT NULL, `session_id` varchar(32) NOT NULL, `referer` varchar(255) DEFAULT NULL, `user_agent` varchar(255) DEFAULT NULL, `url` TEXT DEFAULT NULL, INDEX (`time`) ) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci
DROP TABLE IF EXISTS `{prefix}_menus`;
CREATE TABLE `{prefix}_menus` ( `id` int(11) NOT NULL AUTO_INCREMENT, `index_id` int(11) NOT NULL, `parent` varchar(20) NOT NULL, `level` smallint(2) NOT NULL, `language` varchar(2) NOT NULL, `menu_text` varchar(100) NOT NULL, `menu_tooltip` varchar(100) NOT NULL, `accesskey` varchar(1) NOT NULL, `menu_order` int(11) NOT NULL, `menu_url` varchar(255) NOT NULL, `menu_target` varchar(6) NOT NULL, `alias` varchar(20) NOT NULL, `published` enum('0','1','2','3') NOT NULL DEFAULT '1', PRIMARY KEY (`id`) ) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci
DROP TABLE IF EXISTS `{prefix}_modules`;
CREATE TABLE `{prefix}_modules` ( `id` int(11) NOT NULL AUTO_INCREMENT, `owner` varchar(20) NOT NULL, `module` varchar(64) NOT NULL, `config` text DEFAULT NULL, PRIMARY KEY (`id`) ) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci
DROP TABLE IF EXISTS `{prefix}_personnel`;
CREATE TABLE `{prefix}_personnel` ( `id` int(11) NOT NULL AUTO_INCREMENT, `module_id` int(11) NOT NULL, `category_id` int(11) NOT NULL, `name` varchar(50) NOT NULL, `position` varchar(100) NOT NULL, `detail` varchar(255) NOT NULL, `address` varchar(255) NOT NULL, `phone` varchar(20) NOT NULL, `email` varchar(255) NOT NULL, `picture` varchar(15) NOT NULL, `order` tinyint(2) NOT NULL, PRIMARY KEY (`id`) ) ENGINE=MyISAM DEFAULT CHARSET=utf8
DROP TABLE IF EXISTS `{prefix}_portfolio`;
CREATE TABLE `{prefix}_portfolio` ( `id` int(11) NOT NULL AUTO_INCREMENT, `module_id` int(11) NOT NULL, `title` varchar(255) NOT NULL, `keywords` varchar(255) NOT NULL, `detail` text NOT NULL, `create_date` int(11) NOT NULL, `image` varchar(15) NOT NULL, `url` varchar(255) NOT NULL, `published` enum('0','1') NOT NULL DEFAULT '1', `visited` int(11) NOT NULL, PRIMARY KEY (`id`) ) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci
DROP TABLE IF EXISTS `{prefix}_tags`;
CREATE TABLE `{prefix}_tags` ( `id` int(11) NOT NULL AUTO_INCREMENT, `tag` text NOT NULL, `count` int(11) NOT NULL, PRIMARY KEY (`id`) ) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci
DROP TABLE IF EXISTS `{prefix}_textlink`;
CREATE TABLE `{prefix}_textlink` ( `id` int(11) NOT NULL AUTO_INCREMENT, `text` text NOT NULL, `url` text NOT NULL, `publish_start` int(11) NOT NULL, `publish_end` int(11) NOT NULL, `logo` text NOT NULL, `width` int(11) NOT NULL, `height` int(11) NOT NULL, `type` varchar(11) NOT NULL, `name` varchar(11) NOT NULL, `published` smallint(1) NOT NULL DEFAULT 1, `link_order` smallint(2) NOT NULL, `last_preview` int(11) DEFAULT NULL, `description` varchar(49) NOT NULL, `template` text DEFAULT NULL, `target` varchar(6) NOT NULL, PRIMARY KEY (`id`) ) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci
DROP TABLE IF EXISTS `{prefix}_user`;
CREATE TABLE `{prefix}_user` ( `id` int(11) NOT NULL AUTO_INCREMENT, `password` varchar(50) NOT NULL, `token` varchar(50) DEFAULT NULL, `name` varchar(150) DEFAULT NULL, `displayname` varchar(50) DEFAULT NULL, `sex` varchar(1) DEFAULT NULL, `email` varchar(50) NOT NULL, `salt` varchar(32) NOT NULL, `idcard` varchar(13) DEFAULT NULL, `birthday` date DEFAULT NULL, `website` varchar(255) DEFAULT NULL, `company` varchar(64) DEFAULT NULL, `icon` varchar(24) DEFAULT NULL, `create_date` int(11) NOT NULL, `visited` int(11) DEFAULT NULL, `lastvisited` int(11) DEFAULT NULL, `ip` varchar(50) DEFAULT NULL, `ban` int(11) DEFAULT NULL, `point` int(11) DEFAULT NULL, `post` int(11) DEFAULT NULL, `reply` int(11) DEFAULT 0, `address1` varchar(64) DEFAULT NULL, `address2` varchar(64) DEFAULT NULL, `provinceID` smallint(3) DEFAULT NULL, `province` varchar(64) DEFAULT NULL, `zipcode` varchar(5) DEFAULT NULL, `country` varchar(2) DEFAULT NULL, `phone1` varchar(20) DEFAULT NULL, `phone2` varchar(20) DEFAULT NULL, `activatecode` varchar(32) NOT NULL, `status` tinyint(1) NOT NULL, `social` tinyint(4) NOT NULL, `session_id` varchar(32) DEFAULT NULL, `active` tinyint(1) NOT NULL DEFAULT 0, `permission` text DEFAULT NULL, PRIMARY KEY (`id`) ) ENGINE=MyISAM DEFAULT CHARSET=utf8
DROP TABLE IF EXISTS `{prefix}_useronline`;
CREATE TABLE `{prefix}_useronline` ( `member_id` int(11) NOT NULL, `displayname` varchar(50) DEFAULT NULL, `session` varchar(32) NOT NULL, `time` int(11) NOT NULL, `ip` varchar(50) DEFAULT NULL, PRIMARY KEY (`session`) ) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci
DROP TABLE IF EXISTS `{prefix}_video`;
CREATE TABLE `{prefix}_video` ( `id` int(11) NOT NULL AUTO_INCREMENT, `module_id` int(11) NOT NULL, `youtube` varchar(11) NOT NULL, `topic` text NOT NULL, `description` text NOT NULL, `views` int(11) NOT NULL, `last_update` int(11) NOT NULL, PRIMARY KEY (`id`) ) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci
INSERT INTO `{prefix}_emailtemplate` (`module`, `email_id`, `language`, `from_email`, `copy_to`, `name`, `subject`, `detail`, `last_update`) VALUES ('member','1','th','','','ตอบรับการสมัครสมาชิกใหม่ (ยืนยันสมาชิก)','ตอบรับการสมัครสมาชิก %WEBTITLE%','<div style="padding: 10px;  background-color: rgb(247, 247, 247);">\r\n<table style=" border-collapse: collapse;">\r\n	<tbody>\r\n		<tr>\r\n			<th style="border-width: 1px; border-style: none solid; border-color: rgb(59, 89, 152); padding: 5px; text-align: left; color: rgb(255, 255, 255); font-family: tahoma; font-size: 9pt; background-color: rgb(59, 89, 152);">ยินดีต้อนรับสมาชิกใหม่ %WEBTITLE%</th>\r\n		</tr>\r\n		<tr>\r\n			<td style="border-width: 1px; border-style: none solid solid; border-color: rgb(204, 204, 204) rgb(204, 204, 204) rgb(59, 89, 152); padding: 15px; line-height: 1.8em; font-family: tahoma; font-size: 9pt;">ขอขอบคุณสำหรับการลงทะเบียนกับเรา บัญชีใหม่ของคุณได้รับการติดตั้งเรียบร้อยแล้วและคุณสามารถเข้าระบบได้โดยใช้รายละเอียดด้านล่างนี้<br>\r\n			<br>\r\n			ที่อยู่อีเมล : <strong>%EMAIL%</strong><br>\r\n			รหัสผ่าน&nbsp; : <strong>%PASSWORD%</strong><br>\r\n			<br>\r\n			ก่อนอื่นคุณต้องกลับไปยืนยันการสมัครสมาชิกที่ <a href="%WEBURL%index.php?module=activate&amp;id=%ID%" rel="nofollow">%WEBURL%index.php?module=activate&amp;id=%ID%</a></td>\r\n		</tr>\r\n		<tr>\r\n			<td style="padding: 15px; color: rgb(153, 153, 153); font-family: tahoma; font-size: 8pt;">ด้วยความขอบคุณ <a href="mailto:%ADMINEMAIL%" rel="nofollow">เว็บมาสเตอร์</a></td>\r\n		</tr>\r\n	</tbody>\r\n</table>\r\n</div>','1473600064');
INSERT INTO `{prefix}_emailtemplate` (`module`, `email_id`, `language`, `from_email`, `copy_to`, `name`, `subject`, `detail`, `last_update`) VALUES ('member','1','en','','','Client Signup (Activate)','Welcome %WEBTITLE%','<div style="padding: 10px; background-color: rgb(247, 247, 247);">\r\n<table style="border-collapse: collapse;">\r\n	<tbody>\r\n		<tr>\r\n			<th style="border-width: 1px; border-style: none solid; border-color: rgb(59, 89, 152); padding: 5px; text-align: left; color: rgb(255, 255, 255); font-family: tahoma; font-size: 9pt; background-color: rgb(59, 89, 152);">Welcome %WEBTITLE%</th>\r\n		</tr>\r\n		<tr>\r\n			<td style="border-width: 1px; border-style: none solid solid; border-color: rgb(204, 204, 204) rgb(204, 204, 204) rgb(59, 89, 152); padding: 15px; line-height: 1.8em; font-family: tahoma; font-size: 9pt;">Thank you for signing up with us. Your new account has been setup and you can now login to our client area using the details below.<br>\r\n			<br>\r\n			E-mail : <strong>%EMAIL%</strong><br>\r\n			Password : <strong>%PASSWORD%</strong><br>\r\n			<br>\r\n			Please visit and activate users&nbsp;at <a href="%WEBURL%index.php?module=activate&amp;id=%ID%" rel="nofollow">%WEBURL%index.php?module=activate&amp;id=%ID%</a></td>\r\n		</tr>\r\n		<tr>\r\n			<td style="padding: 15px; color: rgb(153, 153, 153); font-family: tahoma; font-size: 8pt;">With thank <a href="mailto:%ADMINEMAIL%" rel="nofollow">Webmaster</a></td>\r\n		</tr>\r\n	</tbody>\r\n</table>\r\n</div>','1378257446');
INSERT INTO `{prefix}_emailtemplate` (`module`, `email_id`, `language`, `from_email`, `copy_to`, `name`, `subject`, `detail`, `last_update`) VALUES ('member','2','th','','','ตอบรับการสมัครสมาชิกใหม่ (ไม่ต้องยืนยันสมาชิก)','ตอบรับการสมัครสมาชิก %WEBTITLE%','<div style="padding: 10px; background-color: rgb(247, 247, 247);">\n<table style="border-collapse: collapse;">\n	<tbody>\n		<tr>\n			<th style="border-width: 1px; border-style: none solid; border-color: rgb(59, 89, 152); padding: 5px; text-align: left; color: rgb(255, 255, 255); font-family: tahoma; font-size: 9pt; background-color: rgb(59, 89, 152);">ยินดีต้อนรับสมาชิกใหม่ %WEBTITLE%</th>\n		</tr>\n		<tr>\n			<td style="border-width: 1px; border-style: none solid solid; border-color: rgb(204, 204, 204) rgb(204, 204, 204) rgb(59, 89, 152); padding: 15px; line-height: 1.8em; font-family: tahoma; font-size: 9pt;">ขอขอบคุณสำหรับการลงทะเบียนกับเรา บัญชีใหม่ของคุณได้รับการติดตั้งเรียบร้อยแล้วและคุณสามารถเข้าระบบได้โดยใช้รายละเอียดด้านล่างนี้<br />\n			<br />\n			ที่อยู่อีเมล : <strong>%EMAIL%</strong><br />\n			รหัสผ่าน&nbsp; : <strong>%PASSWORD%</strong><br />\n			<br />\n			คุณสามารถกลับไปเข้าระบบได้ที่ <a href="%WEBURL%">%WEBURL%</a></td>\n		</tr>\n		<tr>\n			<td style="padding: 15px; color: rgb(153, 153, 153); font-family: tahoma; font-size: 8pt;">ด้วยความขอบคุณ <a href="mailto:%ADMINEMAIL%">เว็บมาสเตอร์</a></td>\n		</tr>\n	</tbody>\n</table>\n</div>\n','1473599703');
INSERT INTO `{prefix}_emailtemplate` (`module`, `email_id`, `language`, `from_email`, `copy_to`, `name`, `subject`, `detail`, `last_update`) VALUES ('member','2','en','','','Client Signup (no Activate)','Welcome %WEBTITLE%','<div style="padding: 10px; background-color: rgb(247, 247, 247);">\n<table style="border-collapse: collapse;">\n	<tbody>\n		<tr>\n			<th style="border-width: 1px; border-style: none solid; border-color: rgb(59, 89, 152); padding: 5px; text-align: left; color: rgb(255, 255, 255); font-family: tahoma; font-size: 9pt; background-color: rgb(59, 89, 152);">Welcome %WEBTITLE%</th>\n		</tr>\n		<tr>\n			<td style="border-width: 1px; border-style: none solid solid; border-color: rgb(204, 204, 204) rgb(204, 204, 204) rgb(59, 89, 152); padding: 15px; line-height: 1.8em; font-family: tahoma; font-size: 9pt;">Thank you for signing up with us. Your new account has been setup and you can now login to our client area using the details below.<br />\n			<br />\n			E-mail: <strong>%EMAIL%</strong><br />\n			Password : <strong>%PASSWORD%</strong><br />\n			<br />\n			To login, visit <a href="%WEBURL%">%WEBURL%</a></td>\n		</tr>\n		<tr>\n			<td style="padding: 15px; color: rgb(153, 153, 153); font-family: tahoma; font-size: 8pt;">With thank <a href="mailto:%ADMINEMAIL%">Webmaster</a></td>\n		</tr>\n	</tbody>\n</table>\n</div>\n','1473599844');
INSERT INTO `{prefix}_emailtemplate` (`module`, `email_id`, `language`, `from_email`, `copy_to`, `name`, `subject`, `detail`, `last_update`) VALUES ('member','3','th','','','ขอรหัสผ่านใหม่','รหัสผ่านของคุณใน %WEBTITLE%','<div style="padding: 10px;  background-color: rgb(247, 247, 247);">\r\n<table style=" border-collapse: collapse;">\r\n	<tbody>\r\n		<tr>\r\n			<th style="border-width: 1px; border-style: none solid; border-color: rgb(59, 89, 152); padding: 5px; text-align: left; color: rgb(255, 255, 255); font-family: tahoma; font-size: 9pt; background-color: rgb(59, 89, 152);">รหัสผ่านของคุณใน %WEBTITLE%</th>\r\n		</tr>\r\n		<tr>\r\n			<td style="border-width: 1px; border-style: none solid solid; border-color: rgb(204, 204, 204) rgb(204, 204, 204) rgb(59, 89, 152); padding: 15px; line-height: 1.8em; font-family: tahoma; font-size: 9pt;">รหัสผ่านใหม่ของคุณถูกส่งมาจากระบบอัตโนมัติ เมื่อ %TIME%<br />\r\n			ไม่ว่าคุณจะได้ทำการขอรหัสผ่านใหม่หรือไม่ก็ตาม โปรดใช้รหัสผ่านใหม่นี้กับบัญชีของคุณ<br />\r\n			(ถ้าคุณไม่ได้ดำเนินการนี้ด้วยตัวเอง อาจมีผู้พยายามเข้าไปเปลี่ยนแปลงข้อมูลส่วนตัวของคุณ)<br />\r\n			<br />\r\n			ที่อยู่อีเมล : <strong>%EMAIL%</strong><br />\r\n			รหัสผ่าน : <strong>%PASSWORD%</strong><br />\r\n			<br />\r\n			คุณสามารถกลับไปเข้าระบบและแก้ไขข้อมูลส่วนตัวของคุณใหม่ได้ที่ <a href="%WEBURL%">%WEBURL%</a></td>\r\n		</tr>\r\n		<tr>\r\n			<td style="padding: 15px; color: rgb(153, 153, 153); font-family: tahoma; font-size: 8pt;">ด้วยความขอบคุณ <a href="mailto:%ADMINEMAIL%">เว็บมาสเตอร์</a></td>\r\n		</tr>\r\n	</tbody>\r\n</table>\r\n</div>\r\n','1473599666');
INSERT INTO `{prefix}_emailtemplate` (`module`, `email_id`, `language`, `from_email`, `copy_to`, `name`, `subject`, `detail`, `last_update`) VALUES ('member','3','en','','','Request new password','Your password in %WEBTITLE%','<div style="padding: 10px; background-color: rgb(247, 247, 247);">\r\n<table style="border-collapse: collapse;">\r\n	<tbody>\r\n		<tr>\r\n			<th style="border-width: 1px; border-style: none solid; border-color: rgb(59, 89, 152); padding: 5px; text-align: left; color: rgb(255, 255, 255); font-family: tahoma; font-size: 9pt; background-color: rgb(59, 89, 152);">Your new password for use in %WEBTITLE%</th>\r\n		</tr>\r\n		<tr>\r\n			<td style="border-width: 1px; border-style: none solid solid; border-color: rgb(204, 204, 204) rgb(204, 204, 204) rgb(59, 89, 152); padding: 15px; line-height: 1.8em; font-family: tahoma; font-size: 9pt;">Your new password is sent automatically on %TIME%<br />\r\n			Whether you do this or not. Use this new password for your account<br />\r\n			(If you do not do this yourself. May have tried to change your personal information)<br />\r\n			<br />\r\n			E-mail : <strong>%EMAIL%</strong><br />\r\n			Password : <strong>%PASSWORD%</strong><br />\r\n			<br />\r\n			You can return to the login and edit your profile at <a href="%WEBURL%">%WEBURL%</a></td>\r\n		</tr>\r\n		<tr>\r\n			<td style="padding: 15px; color: rgb(153, 153, 153); font-family: tahoma; font-size: 8pt;">With thanks <a href="mailto:%ADMINEMAIL%">Webmaster</a></td>\r\n		</tr>\r\n	</tbody>\r\n</table>\r\n</div>\r\n','1473599676');
INSERT INTO `{prefix}_emailtemplate` (`module`, `email_id`, `language`, `from_email`, `copy_to`, `name`, `subject`, `detail`, `last_update`) VALUES ('edocument','1','th','','','แจ้งการส่งเอกสาร','มีเอกสารส่งถึงคุณใน %WEBTITLE%','<div style="padding: 10px; background-color: rgb(247, 247, 247);">\r\n<table style="border-collapse: collapse;">\r\n	<tbody>\r\n		<tr>\r\n			<th style="border-width: 1px; border-style: none solid; border-color: rgb(59, 89, 152); padding: 5px; text-align: left; color: rgb(255, 255, 255); font-family: tahoma; font-size: 9pt; background-color: rgb(59, 89, 152);">มีเอกสารส่งถึงคุณใน %WEBTITLE%</th>\r\n		</tr>\r\n		<tr>\r\n			<td style="border-width: 1px; border-style: none solid solid; border-color: rgb(204, 204, 204) rgb(204, 204, 204) rgb(59, 89, 152); padding: 15px; line-height: 1.8em; font-family: tahoma; font-size: 9pt;">เรียนคุณ %NAME%<br>\r\n			<br>\r\n			มีเอกสารใหม่ส่งถึงคุณ เมื่อ %TIME%<br>\r\n			<br>\r\n			คุณสามารถตรวจสอบรายการเอกสารของคุณได้ที่ <a href="%URL%" rel="nofollow">%URL%</a> (คุณอาจต้องเข้าระบบก่อน)</td>\r\n		</tr>\r\n		<tr>\r\n			<td style="padding: 15px; color: rgb(153, 153, 153); font-family: tahoma; font-size: 8pt;">ด้วยความขอบคุณ <a href="mailto:%ADMINEMAIL%" rel="nofollow">เว็บมาสเตอร์</a></td>\r\n		</tr>\r\n	</tbody>\r\n</table>\r\n</div>','1377480437');
INSERT INTO `{prefix}_emailtemplate` (`module`, `email_id`, `language`, `from_email`, `copy_to`, `name`, `subject`, `detail`, `last_update`) VALUES ('edocument','1','en','','','Shipping documents','A document sent to you in %WEBTITLE%','<div style="padding: 10px; background-color: rgb(247, 247, 247);">\r\n<table style="border-collapse: collapse;">\r\n	<tbody>\r\n		<tr>\r\n			<th style="border-width: 1px; border-style: none solid; border-color: rgb(59, 89, 152); padding: 5px; text-align: left; color: rgb(255, 255, 255); font-family: tahoma; font-size: 9pt; background-color: rgb(59, 89, 152);">A document sent to you in %WEBTITLE%</th>\r\n		</tr>\r\n		<tr>\r\n			<td style="border-width: 1px; border-style: none solid solid; border-color: rgb(204, 204, 204) rgb(204, 204, 204) rgb(59, 89, 152); padding: 15px; line-height: 1.8em; font-family: tahoma; font-size: 9pt;">dear %NAME%<br>\r\n			<br>\r\n			The new document is sent to you on %TIME%<br>\r\n			<br>\r\n			You can check your document at. <a href="%URL%" rel="nofollow">%URL%</a> (You may need to login first)</td>\r\n		</tr>\r\n		<tr>\r\n			<td style="padding: 15px; color: rgb(153, 153, 153); font-family: tahoma; font-size: 8pt;">With thanks <a href="mailto:%ADMINEMAIL%" rel="nofollow">Webmaster</a></td>\r\n		</tr>\r\n	</tbody>\r\n</table>\r\n</div>','1473601020');
